### PR TITLE
Update Terraform GitHub provider to v6

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by damienwebdev** [comment]
```
       ~ resource "github_branch_protection" "repositories" {
        id                              = "BPR_kwDOGta9mM4B0QmJ"
      ~ pattern                         = "main" -> "*"
        # (9 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

Is this intentional?

**Comment by sprankhub** [comment]
Yes, it is. I think @Vinai temporarily changed this, so that he is able to work on something in a separate branch. But in general, the pattern should be `*` as for each other repository.

**Comment by sprankhub** [comment]
@damienwebdev, since I answered your question, could you review again and approve if you are fine with the changes? :pray:

**Review by damienwebdev — APPROVED** [review]

**Pull request merged**
