### PR TITLE
Add Support For Archiving Repositories

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Review by damienwebdev — APPROVED** [review]
LGTM!

**Comment by damienwebdev** [comment]
Actually @sprankhub why are there additional plans? Were there manual modifications that this is reverting?

**Comment by sprankhub** [comment]
> Were there manual modifications that this is reverting?

Seems so.

`CODEOWNERS`: Since you force-pushed, you changed the default `CODEOWNERS` file, which was already in place. Terraform currently makes sure that the `CODEOWNERS` file is always like we once defined it ^^

Not sure why the `tech-lead` did not have `maintain` rights at the moment, but probably also due to a manual change.

**Pull request merged**
